# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tetragon/stack.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tetragon/stack.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14tetragon/stack.proto\x12\x08tetragon\"/\n\x0cStackAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x04\x12\x0e\n\x06symbol\x18\x02 \x01(\t\"7\n\nStackTrace\x12)\n\taddresses\x18\x01 \x03(\x0b\x32\x16.tetragon.StackAddress\"-\n\x0fStackTraceLabel\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x04\"\x9f\x01\n\x0eStackTraceNode\x12\'\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0b\x32\x16.tetragon.StackAddress\x12\r\n\x05\x63ount\x18\x02 \x01(\x04\x12)\n\x06labels\x18\x03 \x03(\x0b\x32\x19.tetragon.StackTraceLabel\x12*\n\x08\x63hildren\x18\x04 \x03(\x0b\x32\x18.tetragon.StackTraceNodeB,Z*github.com/cilium/tetragon/api/v1/tetragonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tetragon.stack_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/cilium/tetragon/api/v1/tetragon'
  _globals['_STACKADDRESS']._serialized_start=34
  _globals['_STACKADDRESS']._serialized_end=81
  _globals['_STACKTRACE']._serialized_start=83
  _globals['_STACKTRACE']._serialized_end=138
  _globals['_STACKTRACELABEL']._serialized_start=140
  _globals['_STACKTRACELABEL']._serialized_end=185
  _globals['_STACKTRACENODE']._serialized_start=188
  _globals['_STACKTRACENODE']._serialized_end=347
# @@protoc_insertion_point(module_scope)
